---  # disable_ipv6/tasks/main.yml

- name: Disable IPv6 in the kernel parameters
  ansible.posix.sysctl:
    name: "{{item}}"
    value: "1"
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Disable IPv6 permanently
  ansible.builtin.copy:
    dest: /etc/sysctl.d/disable-ipv6.conf
    content: |
      # /etc/sysctl.d/disable-ipv6.conf
      #
      # Disable IPv6
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1

- name: Configure SSH for IPv4 only
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: "{{item.from}}"
    replace: "{{item.to}}"
  loop:
    - from: "^#AddressFamily any"
      to: "AddressFamily inet"
    - from: "^#ListenAddress 0.0.0.0"
      to: "ListenAddress 0.0.0.0"
  notify: Reload SSH configuration

- name: Flush handlers
  meta: flush_handlers

...
