---  # local.yml

- hosts: localhost

  pre_tasks:

    - name: Check out Effective User ID
      set_fact:
        eff_uid: "{{lookup('pipe', 'id -u')}}"
        locale: en_US.UTF-8

    - block:
        - debug:
            msg: "Please run this program as root."
        - meta: end_play
      when: eff_uid|int != 0

    - name: Make sure we're running Rocky Linux 9.x
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Rocky"
          - ansible_distribution_major_version is version('9', '=')
        fail_msg: "Please run this playbook on Rocky Linux 9.x only."

    - name: Include encrypted variables
      ansible.builtin.include_vars:
        file: vars/secret.yml

    - debug:
        var: root_passwd

  roles:
    - configure_locale
    - enable_selinux
    - setup_root
    - configure_sudo
    - configure_bash
    - configure_vim
    - repos_official
    - repos_epel
    - repo_lynis
    - install_tools

...
