---  # local.yml

- hosts: localhost

  pre_tasks:

    - name: Make sure we're running Rocky Linux 9.x
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Rocky"
          - ansible_distribution_major_version is version('9', '=')
        fail_msg: "Please run this playbook on Rocky Linux 9.x only."

...
